# Generated by Django 5.2 on 2025-11-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dat',
            new_name='pub_date',
        ),
    ]
